name: test
on:
  pull_request:
  push:
    branches: [main]
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go mod tidy && git diff --exit-code go.mod && (test ! -f go.sum || git diff --exit-code go.sum)
      - run: go vet ./...
      - run: go build ./...
      - run: go test -race ./...

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true

      - name: run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
